// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keixtwrzwfpsafbhezyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaXh0d3J6d2Zwc2FmYmhlenloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzk3NDMsImV4cCI6MjA2NTgxNTc0M30.f1q-ySv4lfNDPPcN3FN1QKPMMqBwMo2-sRuBrkeuev8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);